### ISSUE TITLE
pull下来后，运行不起来（please retry with version 4.3 or newer）

### ISSUE THREAD

**Issue by yfengtech** [rengwuxian/WeCompose#2]
将代码拉下来后无法运行，提示需要更新版本到4.3，然而我能更新的最新版是android_ studio 4.2 Beta 4
求解~

报错信息：
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.3 or newer.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
com.intellij.openapi.externalSystem.model.ExternalSystemException: This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.3 or newer.
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.addBuildModels(ProjectImportAction.java:259)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:117)
...

**Comment by yfengtech** [comment]
I found this. 
https://androidstudio.googleblog.com/2021/02/android-studio-arctic-fox-canary-6.html
